### PR TITLE
updated cf-create-org to use v3 api

### PR DESCRIPTION
**Pull request by kwadwok15**
## Changes proposed in this pull request:
- changed logic for deleting "admin" from new created org. 
- 
-

## security considerations
none

### CODE REVIEW

**Comment by kwadwok15** [comment]
Changed the logic for deleting "admin" user from newly created org. 
New logic: v3 api does not associate users to an org but rather user is associate to a role and role is associated to an org. To achieve the same behavior the script 
1. pull "admin" user guid 
2. pull org guid 
3. pull role guid filtered by role_type"organization_user", admin user guid, and org guid
4. then delete the role based on role guid. 

Next step. Test the script in CF stage environment.

**Review by ccostino — COMMENTED** [review]
This looks good so far, @kwadwok15!  Only one thing caught my eye, which was escaping some of the double quotes (`"`) - it looks like this might not be needed though, looking at the previous line that is being replaced?

**Comment by kwadwok15** [comment]
@ccostino, noted

**Review by ccostino — APPROVED** [review]
Looks good, thanks @kwadwok15!

**Comment by kwadwok15** [comment]
thanks @ccostino  merging PR now.

**Pull request merged**
