### PR TITLE
Add new audit script for analyzing brokered service costs

### PR DESCRIPTION
**Pull request by ccostino**
This changeset introduces the very beginnings of a new script to help audit our brokered service costs.  At the moment it requires the JSON output from `awscli` API calls.  Only RDS, Redis, and Elasticsearch processing is implemented at this time, but there is support for parsing tags for services that require a separate API call (e.g., Redis and Elasticsearch).

This could grow to make the calls directly though using `boto3`, making this processing much more convenient.

## Changes proposed in this pull request:
- Add a new Python script to process AWS brokered service information

## security considerations
- Retrieves metadata about running AWS services within the platform; requires platform access to run

### CODE REVIEW

**Review by onelittlebecca — COMMENTED** [review]
Looks good -- have you given it a try yet? Interested to see the outputs and if it pulls all the things or misses some stuff.

**Review by onelittlebecca — APPROVED** [review]
I see what you did there! adding in the aws specific deets! nice! explains why it is getting some improved/enhanced outputs now!

**Comment by ccostino** [comment]
D'oh!  It's 730 hours per month in the pricing calculations, not 750.  Need to adjust that...

**Review by onelittlebecca — APPROVED** [review]
looks good! woot woot!

**Comment by ccostino** [comment]
This now includes processing for Redis instances and AWS resource tag processing for when that's needed!

**Pull request merged**
